#! /bin/sh

bspc config border_width        0
bspc config window_gap		14
bspc config top_padding		18

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config auto_cancel		true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
